src/main/scala/firrtl_interpreter/DependencyGraph.scala
src/main/scala/firrtl_interpreter/FirrtlRepl.scala
src/main/scala/firrtl_interpreter/LoFirrtlExpressionEvaluator.scala
src/test/resources/FullAdder.ir
src/test/scala/firrtl_interpreter/SourceInfoSpec.scala

shows source info during expression evaluation and exceptions (when present)

Show sourceinfo

---

build.sbt

We get (reproducible under load) build failures:
[info] - should evaluate multiply SIntValues correctly *** FAILED ***
[info]   firrtl_interpreter.InterpreterException: error: ConcreteUInt(-1, 1) bad width 1 needs 2
[info]   at firrtl_interpreter.ConcreteUInt.<init>(Concrete.scala:275)
[info]   at firrtl_interpreter.Concrete$.apply(Concrete.scala:244)
[info]   at firrtl_interpreter.LoFirrtlExpressionEvaluator.evaluate(LoFirrtlExpressionEvaluator.scala:354)
[info]   at firrtl_interpreter.LoFirrtlExpressionEvaluator.mathPrimitive(LoFirrtlExpressionEvaluator.scala:144)
[info]   at firrtl_interpreter.LoFirrtlExpressionEvaluatorSpec$$anonfun$4$$anonfun$apply$mcV$sp$2.apply$mcVI$sp(LoFirrtlExpressionEvaluatorSpec.scala:117)
[info]   at …

Serialize tests.

---

src/main/scala/firrtl_interpreter/CircuitState.scala
src/main/scala/firrtl_interpreter/FirrtlRepl.scala
src/main/scala/firrtl_interpreter/FirrtlTerp.scala
src/main/scala/firrtl_interpreter/InterpretiveTester.scala
src/main/scala/firrtl_interpreter/LoFirrtlExpressionEvaluator.scala
src/main/scala/firrtl_interpreter/Timer.scala
src/main/scala/vcd/VCD.scala
src/test/scala/firrtl_interpreter/GCDTester.scala
src/test/scala/firrtl_interpreter/LifeCellSpec.scala
src/test/scala/firrtl_interpreter/TimerSpec.scala
src/test/scala/vcd/VCDSpec.scala

better vcd management
repl knows about vcd now
timer singleton removed
ordered exec works

Vcd support

---

src/main/scala/firrtl_interpreter/CircuitState.scala
src/main/scala/firrtl_interpreter/Concrete.scala
src/main/scala/firrtl_interpreter/ConcreteSIntSpec.scala
src/main/scala/firrtl_interpreter/DependencyGraph.scala
src/main/scala/firrtl_interpreter/ExpressionExecutionStack.scala
src/main/scala/firrtl_interpreter/FirrtlTerp.scala
src/main/scala/firrtl_interpreter/LoFirrtlExpressionEvaluator.scala
src/main/scala/firrtl_interpreter/Memory.scala
src/main/scala/firrtl_interpreter/ToLoFirrtl.scala
src/main/scala/firrtl_interpreter/TypeInstanceFactory.scala
src/main/scala/firrtl_interpreter/package.scala
src/main/scala/vcd/VCD.scala
src/test/scala/firrtl_interpreter/CastingSpec.scala
src/test/scala/firrtl_interpreter/CircuitStateSpec.scala
src/test/scala/firrtl_interpreter/DynamicMemorySearch.scala
src/test/scala/firrtl_interpreter/GCDTester.scala
src/test/scala/firrtl_interpreter/InterpretiveTesterSpec.scala
src/test/scala/firrtl_interpreter/LifeCellSpec.scala
src/test/scala/firrtl_interpreter/LoFirrtlExpressionEvaluatorSpec.scala
src/test/scala/firrtl_interpreter/MemorySpec.scala
src/test/scala/firrtl_interpreter/RegisterSpec.scala
src/test/scala/firrtl_interpreter/TestUtils.scala
src/test/scala/firrtl_interpreter/TestUtilsSpec.scala
src/test/scala/firrtl_interpreter/TimerSpec.scala
src/test/scala/firrtl_interpreter/TypeInstanceFactorySpec.scala
src/test/scala/vcd/VCDSpec.scala

Keeps firrtl-interpreter up to date with firrtl

Refactor interpreter for IR-cleanup #191 in ucb-bar/firrtl

---

src/main/scala/firrtl_interpreter/FirrtlRepl.scala

Fixes string completion of the input ports for the poke command in the repl

Fixed string completer for pokes

---

README.md

re-write opening to readme file

---

src/main/scala/firrtl_interpreter/CircuitState.scala
src/main/scala/firrtl_interpreter/LoFirrtlExpressionEvaluator.scala
src/test/scala/firrtl_interpreter/CarryOrChain3.scala
src/test/scala/firrtl_interpreter/CarryOrChain6.scala
src/test/scala/firrtl_interpreter/LoFirrtlExpressionEvaluatorSpec.scala
src/test/scala/firrtl_interpreter/OutputAsSourceSpec.scala

Fixes a problem reported in issue #28 
Now resolves dependencies on module outputs the same as it would other wires.

Fix carry or chain

---

src/main/scala/firrtl_interpreter/Concrete.scala
src/test/scala/firrtl_interpreter/ConcreteSpec.scala
src/test/scala/firrtl_interpreter/PoisonSpec.scala

Brings interpreter up to date with firrtl for add width calculation

Fix calculation of width in SInt + UInt and UInt + SInt

---

src/main/scala/firrtl_interpreter/CircuitState.scala
src/main/scala/firrtl_interpreter/Concrete.scala
src/main/scala/firrtl_interpreter/FirrtlTerp.scala
src/main/scala/firrtl_interpreter/InterpretiveTester.scala
src/test/scala/firrtl_interpreter/CircuitStateSpec.scala
src/test/scala/firrtl_interpreter/LifeCellSpec.scala
src/test/scala/firrtl_interpreter/RegisterCycleTest.scala

Seems to fix Issue #37, I probably need to run a few more tests against the tutorials before I'll merge this.  But should be worth testing the problem issue against this version

Init regs issue 37

---

src/main/scala/firrtl_interpreter/CircuitState.scala
src/main/scala/firrtl_interpreter/InterpretiveTester.scala

This pr essentially reverts a change which broke the tutorials.

Revert changes to isStale.

---

src/main/scala/firrtl_interpreter/Concrete.scala

fixed error message that did .toInt on BigInt unnecessarily

---

src/main/scala/firrtl_interpreter/Concrete.scala
src/main/scala/firrtl_interpreter/FirrtlRepl.scala
src/main/scala/firrtl_interpreter/TypeInstanceFactory.scala
src/main/scala/firrtl_interpreter/real/DspRealBlackBox.scala
src/test/scala/firrtl_interpreter/PoisonSpec.scala
src/test/scala/firrtl_interpreter/real/BlackBoxRealSpec.scala

Some fixes based on hacking session yesterday
- rpoke and rpeek work with regex's to specify circuit
- made fixes for poison and black boxes

Hack updates 1

---

src/main/scala/firrtl_interpreter/ToLoFirrtl.scala

Trying to make Firrtl able to use the interpreter

Adhere to new Firrtl Compiler API

---

src/main/scala/firrtl_interpreter/ToLoFirrtl.scala
src/main/scala/firrtl_interpreter/package.scala

I've been trying to get everything in dsp-framework working, and this was necessary to get things compiling.
These fixes seem strange to me- it seems like these lines should have been incorrect before.
Also: is this branch the correct place to apply these fixes? I see the same problems in the master branch, but as we are working with rocket I thought the rocket-ready branch was the right branch to be working with.

Fix some compilation errors.

---

src/test/resources/three_deep.fir

This test was just trying to show interpreter could handle nested modules, not worth figuring out how to get memory stuff write so just made a simpler level3 module instead

Fix break introduced in firrtl pr #380

---

src/main/scala/firrtl_interpreter/CircuitState.scala
src/main/scala/firrtl_interpreter/FirrtlRepl.scala
src/main/scala/firrtl_interpreter/FirrtlTerp.scala
src/main/scala/firrtl_interpreter/ReplVcdController.scala
src/main/scala/firrtl_interpreter/TypeInstanceFactory.scala
src/test/scala/firrtl_interpreter/vcd/VCDSpec.scala

Can now set SInt to a negative value from VCD's positive value, when sized appropriately
Refactor TypeInstanceFactory
reduce number of methods
rename some to make usage clearer
Get rid of unnecessary setInput on CircuitState
setValueWithBigInt does the negative value work for SInt with unsigned bigint value

More VCD improvments

---

src/main/scala/firrtl_interpreter/InterpretiveTester.scala

Fixes ucb-bar/chisel-tutorial#65

Fix printing of circuit name

---

src/test/scala/firrtl_interpreter/LoFirrtlExpressionEvaluatorSpec.scala

Expect a PassException on a circuit with a combinational loop,

---

src/main/scala/firrtl_interpreter/FirrtlRepl.scala
src/main/scala/firrtl_interpreter/FirrtlTerp.scala
src/main/scala/firrtl_interpreter/LoFirrtlExpressionEvaluator.scala

```peek``` and ```rpeek``` now only evaluate the portion of the graph specifically necessary to resolve the peeked value
If you want to evalute the whole circuit use ```step``` or ```rpeek .*```
This makes it much easier to use verbose to see the computations being done to figure out the peek
Added arguments to show
```show state``` - shows the state of the circuit, this is the default
```show input``` - the original input supplied.
``` show lofirrtl``` - shows the lowered input

Some small enhancements to the firrtl-repl

---

src/test/scala/firrtl_interpreter/vcd/VCDSpec.scala

fixed illegal call to set log level

---

src/main/scala/firrtl_interpreter/Memory.scala
src/test/scala/firrtl_interpreter/MemoryUsageSpec.scala

setValue for ReadWriteMemory did not have proper match list
fieldDependencies for ReadWriteMemory had wrong label for wmask and was
missing wdata
Added test for read write memory

ReadWrite memory was not processing input signals correctly

---

build.sbt
project/plugins.sbt

Only two real changes:
- build.sbt
- project/plugins.sbt

Update from release

---

src/main/scala/firrtl_interpreter/FirrtlRepl.scala
src/main/scala/firrtl_interpreter/FirrtlTerp.scala
src/main/scala/firrtl_interpreter/InterpretiveTester.scala
src/test/scala/firrtl_interpreter/MemoryUsageSpec.scala

Would be nice to have block versions of these but at least these give access.
One could construct script files to load blocks of memories using mempoke

Add repl commands mempeek and mempoke

---

src/main/scala/firrtl_interpreter/LoFirrtlExpressionEvaluator.scala

Prompted by freechipsproject/firrtl#663.

Convert to new firrtl StringLit.

---

src/main/scala/firrtl_interpreter/ExternalModule.scala
src/main/scala/firrtl_interpreter/LoFirrtlExpressionEvaluator.scala

DspTools won't need to be changed right away.
Fix printstatement bug introduced by firrtl change

Make backward compatibility with black box fix better.

---

src/main/scala/firrtl_interpreter/FirrtlRepl.scala

- Give some feedback when a firrtl file is loaded.
- Give some feedback when a vcd script is loaded
- Now can load vcd in repl, it used to require command line
- New eval command shows how wire got it's current value
- Repl command can be separated with ; (semi-colon), very useful with history

A small package of changes that make the repl more useful.

---

src/main/scala/firrtl_interpreter/CircuitState.scala
src/main/scala/firrtl_interpreter/Driver.scala
src/main/scala/firrtl_interpreter/FirrtlRepl.scala
src/main/scala/firrtl_interpreter/ReplConfig.scala
src/main/scala/firrtl_interpreter/ReplVcdController.scala

Effectively deprecate fr-use-vcd-script, inconsistent generated naming
of targetDir's has doomed it.
Place some guards of setting values from VCD file.  particularly
as circuit is initialized, bad values can occur.

Fix VCD command completion a bit

---

src/main/scala/firrtl_interpreter/LoFirrtlExpressionEvaluator.scala
src/test/scala/firrtl_interpreter/PrintStopSpec.scala

Was printing true, now prints binary value
in sign magnitude format fix for
[Chisel 3 Issue 716](/freechipsproject/chisel3/issues/716)

Printf %b format not working

---

src/LICENSE.txt

Seems like about time I did this.

Add license file

---

src/main/scala/firrtl_interpreter/ToLoFirrtl.scala

Fix for freechipsproject/firrtl#721 and freechipsproject/chisel3#767.

Update ToLoFirrtl in light of annotations refactor.

---

src/main/scala/firrtl_interpreter/vcd/VCD.scala
src/test/scala/firrtl_interpreter/vcd/VCDSpec.scala

in vcd log clock and other one bit signals tracked wrong.
added tests for fix

Fix pr 114 bug

---

src/test/scala/firrtl_interpreter/GCDTester.scala

This makes performance easier to do.
Currently Treadle is approx 20x faster on GCD

Add same GCD test from Treadle

---

src/main/scala/firrtl_interpreter/ExternalModule.scala

Implement new foreach* methods for ExternalModule

---

src/main/scala/firrtl_interpreter/Concrete.scala
src/main/scala/firrtl_interpreter/LoFirrtlExpressionEvaluator.scala
src/main/scala/firrtl_interpreter/Memory.scala
src/main/scala/firrtl_interpreter/package.scala

Adds proper exceptions for places that AsyncReset might be encountered

Better errors for async reset

---

.github/scripts/generateGitClones.gawk
.github/scripts/generateVersionOverrides.gawk
.github/workflows/test.yml

Add dependencies to verify they do work.
Build with: git-clone chisel3 https://github.com/freechipsproject/chisel3.git master
Build with: maven-version firrtl 1.3-SNAPSHOT

Add support for GitHub Workflow caching.

---

.github/scripts/ExtractBuildDependenciesFromPullRequest.gawk
.github/scripts/generateGitClones.gawk
.github/scripts/generateVersionOverrides.gawk
.github/workflows/test.yml

Add support for GitHub Workflows. (#174) …
Update sbt to 1.3.8 (#163)
Update scalacheck to 1.14.3 (#164)
Add support for GitHub Workflow caching. (#175) …

Bring 1.3.x up-to-date with master

---

.scala-steward.conf

Runs on the first of each month

Only run scala-steward once a month

---

README.md
build.sbt
build.sc

Build with: git-clone firrtl https://github.com/freechipsproject/firrtl.git master

Bump SNAPSHOT version.

---

src/main/scala/firrtl_interpreter/CircuitState.scala
src/main/scala/firrtl_interpreter/Driver.scala
src/main/scala/firrtl_interpreter/FirrtlTerp.scala
src/main/scala/firrtl_interpreter/InterpretiveTester.scala
src/main/scala/firrtl_interpreter/NumberMonitor.scala
src/test/scala/firrtl_interpreter/NumberMonitorSpec.scala

Mostly bringing some new special flags to do historgram analysis of wires
Report of wire usage is written out to files
New options control where to write them
NumberMonitor does the analysis

Adding support for fft project

---

.github/workflows/test.yml
.mergify.yml
build.sbt
build.sc
project/plugins.sbt

Change build.sbt and build.sc
Bump firrtl dependency to 1.5-snapshot
Add sbt-pgp plugin

Bump this to 1.5-snapshot

---

build.sbt
build.sc
src/main/scala/firrtl_interpreter/ExternalModule.scala
src/main/scala/firrtl_interpreter/LoFirrtlExpressionEvaluator.scala
src/main/scala/firrtl_interpreter/NumberMonitor.scala
src/main/scala/firrtl_interpreter/real/DspRealBlackBox.scala
src/main/scala/firrtl_interpreter/vcd/VCD.scala

Drop support for Scala 2.11
Mostly involved getting right form of Seq and changing `= Unit` to `= ()`

Add support for Scala 2.13
