- build.sbt
This is primarily in support of our Jenkins regression testing.
> Provide a way to override the default firrtl version.

- .gitignore
- build.sbt
- frepl.sh
- src/main/scala/firrtl_interpreter/Concrete.scala
- src/main/scala/firrtl_interpreter/ConcreteSIntSpec.scala
- src/main/scala/firrtl_interpreter/FirrtlRepl.scala
- src/main/scala/firrtl_interpreter/Memory.scala
- src/main/scala/firrtl_interpreter/package.scala
- src/test/scala/firrtl_interpreter/CastingSpec.scala
- src/test/scala/firrtl_interpreter/ConcreteSpec.scala
- src/test/scala/firrtl_interpreter/LoFirrtlExpressionEvaluatorSpec.scala
- src/test/scala/firrtl_interpreter/TestUtils.scala
ConcreteSInt toString now show S
Added casting test
Found and fixed size bug on SInt - UInt width now max(w1,w2)+2
Better Binary string maker for ConcreteSInt
Re-work figuring how big many bits required for a number to fit in a Concrete UInt or SInt
New Tests for casting
Make main branch depend on development firrtl
script to start repl "frepl.sh"
More changes for SInt width fixes
replace requiredBits with specific versions for UInt and SInt
Some style cleanup
Fixed tests with erroneous notions of SInt width (usually did not take into account positive value needs extra bit for zero sign bit)
> Fix problems with widths and signed numbers

- src/main/scala/firrtl_interpreter/Concrete.scala
- src/test/scala/firrtl_interpreter/DynamicMemorySearch.scala
- src/test/scala/firrtl_interpreter/RandomConcreteSpec.scala
- src/test/scala/firrtl_interpreter/TestUtils.scala
Fixes ```Concrete.randomSInt(width: Int)```, it was possible to generate a value too big for the desired width.  Also fixed it to now return legal negative values.  This is a fix for Issue #18
> Fix random sint

- src/main/scala/firrtl_interpreter/Concrete.scala
- src/test/scala/firrtl_interpreter/ConcreteSpec.scala
This fixes issue #23 
It is necessary to convert to UInt before applying the operations
> Fixed and, or, xor operations when applied to negative SInts

- src/main/scala/firrtl_interpreter/Concrete.scala
- src/main/scala/firrtl_interpreter/InterpretiveTester.scala
- src/main/scala/firrtl_interpreter/LoFirrtlExpressionEvaluator.scala
- src/main/scala/firrtl_interpreter/Memory.scala
- src/main/scala/firrtl_interpreter/TypeInstanceFactory.scala
- src/test/scala/firrtl_interpreter/ConcreteSpec.scala
- src/test/scala/firrtl_interpreter/PoisonSpec.scala
poison is now a value within the ConcreteUInt and ConcreteSInt types.  This allows it flow through the interpreter but be retained.  This PR fixes a problem reported by @jackkoenig where extract bits threw an exception when it encountered a poisoned value
> Refactor poison values so they propagate correctly through interpreter

- src/main/scala/firrtl_interpreter/ExternalModule.scala
Some new methods were added to Expression to support new notions of
map(). BlackBoxOutput needs to implement them.
> Fix broken BlackBoxOutput implementation.

- src/main/scala/firrtl_interpreter/CircuitState.scala
- src/main/scala/firrtl_interpreter/Driver.scala
- src/main/scala/firrtl_interpreter/FirrtlTerp.scala
- src/main/scala/firrtl_interpreter/InterpretiveTester.scala
- src/test/scala/firrtl_interpreter/DriverSpec.scala
- src/test/scala/firrtl_interpreter/GCDTester.scala
- src/test/scala/firrtl_interpreter/LifeCellSpec.scala
see firrtl ComposableOptions
make vcd logger write options safe
calling report will close a pending vcd dump
Depends on [Firrtl PR 337](/ucb-bar/firrtl/pull/337)
Depends on [Chisel PR 325](/ucb-bar/chisel3/pull/325)
> Add execution harness stuff to the interpreter

- src/main/scala/firrtl_interpreter/Driver.scala
- src/main/scala/firrtl_interpreter/ExpressionExecutionStack.scala
- src/main/scala/firrtl_interpreter/FirrtlRepl.scala
- src/main/scala/firrtl_interpreter/InterpretiveTester.scala
Add option `--fint-max-execution-depth` (abbreviated `fmed`) to set the expression evaluation stack depth.
I was running some PFB tests with a large number of taps and exceeded the default of 1000.
> Add option to set expression stack depth.

- src/main/scala/firrtl_interpreter/FirrtlRepl.scala
- src/main/scala/firrtl_interpreter/Script.scala
- src/main/scala/firrtl_interpreter/TypeInstanceFactory.scala
fixed script loading message
lots of run fixes
- run by itself runs 1 line of script
- run n runs next n lines of script
- run reset resets script to line 0
- run set n sets next line of script to n (counts from zero)
- run skip n skips next n lines of script (default 1 if n unspecified)
command may have a comment, delimited by #, this may be used in repl and in scripts
new command poison will poison the whole circuit
> A number of ease of use features for interpreter

- src/main/scala/firrtl_interpreter/CircuitState.scala
- src/main/scala/firrtl_interpreter/FirrtlRepl.scala
- src/main/scala/firrtl_interpreter/FirrtlTerp.scala
- src/main/scala/firrtl_interpreter/InterpretiveTester.scala
- src/main/scala/firrtl_interpreter/ReplConfig.scala
- src/main/scala/firrtl_interpreter/ReplVcdController.scala
- src/main/scala/firrtl_interpreter/TypeInstanceFactory.scala
- src/main/scala/firrtl_interpreter/vcd/VCD.scala
- src/test/scala/firrtl_interpreter/CircuitStateSpec.scala
- src/test/scala/firrtl_interpreter/GCDTester.scala
- src/test/scala/firrtl_interpreter/RegisterSpec.scala
- src/test/scala/firrtl_interpreter/vcd/VCDSpec.scala
VCD now has read method that will read a vcd file and load all data
- The desired scope can be extracted from within outer wrapping scopes
Repl now has support for VCD
- VCD input file can be selected
- VCD file can be run like current script run commands
- Repl script can be autoinvoked at startup
- Combined with VCD, a script that runs the desired VCD can be created and run
- Ths will help verification to run a complex script in order to do concolic testing
Cleaner command implementation for vcd should be propagated to other complex commands
ReplVCD controller needed some changes in order to process VCD
- Ability to clone CircuitState
- More correct ability to poke registers
- Register poke change register's value as RHS
- Handles positive edge transition of clock input (when present) …
> Support for VCD input scripts

- src/main/scala/firrtl_interpreter/FirrtlTerp.scala
I generally don't want the LoFirrtl output printed unless I'm debugging. Running a suite of tests dumps tons of text, which is becoming a problem if I can't not print this.
> [stevo]: log LoFirrtl instead of println so it obeys verbosity flag

- src/main/scala/firrtl_interpreter/CircuitState.scala
- src/main/scala/firrtl_interpreter/DependencyGraph.scala
- src/main/scala/firrtl_interpreter/FirrtlRepl.scala
- src/main/scala/firrtl_interpreter/vcd/VCD.scala
- src/test/resources/fft.fir
- src/test/resources/fft.script
Add wires to scopes when they are first encountered
Update a mythical clock signal as interpreter cycles
Add scopes from wires as they are encountered
Add instance name tracking to dependency graph
Removed requirement that repl only allows vcd output if script is loaded
repl now shows null pointer exceptions without dying
Add fft firrtl file to resources
> A bunch of changes to fix creation of VCD files by interpreter

- .gitignore
It's helpful for me if git ignores /lib added by dsp-framework and/or craft2-chip
> Ignore lib (for rocket build)

- src/main/scala/firrtl_interpreter/CircuitState.scala
- src/main/scala/firrtl_interpreter/DependencyGraph.scala
- src/main/scala/firrtl_interpreter/Driver.scala
- src/main/scala/firrtl_interpreter/FirrtlRepl.scala
- src/main/scala/firrtl_interpreter/FirrtlTerp.scala
- src/main/scala/firrtl_interpreter/InterpretiveTester.scala
- src/main/scala/firrtl_interpreter/LoFirrtlExpressionEvaluator.scala
- src/main/scala/firrtl_interpreter/vcd/VCD.scala
- src/test/scala/firrtl_interpreter/vcd/VCDSpec.scala
By default do not record variables whose names begin with underscore
TimeStamp in VCD logger starts at 0 now instead of -1
A lot of changes to clock management particularly with respect to vcd output
register inits are now handled during register dependency instead of separately
changes to top level module input are logged as happening on clock negative edge
all other circuit changes should take place on positive edge
Registers are now stored independency graph as map to find them easier
Fix minor bug on empty history
> Another round of VCD recording enhancments

- src/main/scala/firrtl_interpreter/FirrtlRepl.scala
- src/main/scala/firrtl_interpreter/FirrtlTerp.scala
- src/main/scala/firrtl_interpreter/InterpretiveTester.scala
- src/test/scala/firrtl_interpreter/RegisterSpec.scala
Per @azidar Should use defname when getting names for external modules
Do better passing of options into interpreter, too many were being lost before
> BlackBox name fix, pass options better into interpreter

- src/main/scala/firrtl_interpreter/DependencyGraph.scala
- src/test/scala/firrtl_interpreter/real/BlackBoxRealSpec.scala
Just a warning for each unmatched ext module for now. 
Resolves Issue #68 
Some style cleanup in dependency graph and black box real spec
> Issue warning on if external module does not have an implementation

- src/test/scala/firrtl_interpreter/vcd/VCDSpec.scala
This is similar to pr ucb-bar/firrtl#392 and ucb-bar/firrtl#399 - fetch the resource as a resource, not as a random file otherwise the test will fail if it is executed anywhere outside of the actual source directory.
> Fetch resource files as resources.

- src/main/scala/firrtl_interpreter/Concrete.scala
- src/test/scala/firrtl_interpreter/ConcreteSpec.scala
- src/test/scala/firrtl_interpreter/LoFirrtlExpressionEvaluatorSpec.scala
Right shift allows shifts bigger than size of thing being shifted
This brings behavior more in line with verilator and other tools
Updated tests for above
Some style cleanup in both files
/chisel3/issue#524
> Right shift can shift all bits out. 

- src/main/scala/firrtl_interpreter/CircuitState.scala
- src/main/scala/firrtl_interpreter/FirrtlTerp.scala
- src/main/scala/firrtl_interpreter/InterpretiveTester.scala
- src/main/scala/firrtl_interpreter/ReplVcdController.scala
- src/main/scala/firrtl_interpreter/vcd/VCD.scala
- src/test/scala/firrtl_interpreter/GCDTester.scala
- src/test/scala/firrtl_interpreter/vcd/VCDSpec.scala
Values dependent on registers could be a half to a full cycle off, now fixed.
Make a constant for "clock" in VCD
Moved control over vcd output clock in to VCD
Fixed apparent flush problem with VCD writing
Some style cleanup
> Fixing discrepancies between interpreter's and verilator's vcd output

- build.sbt
- Added header
- Removed scopt dependency, this should come from firrtl dependency
This will help with PR to update scopt to 3.5.0 in firrtl
> Cleanup of build.sbt

- src/main/scala/firrtl_interpreter/DependencyGraph.scala
- src/main/scala/firrtl_interpreter/ExternalModule.scala
- src/main/scala/firrtl_interpreter/LoFirrtlExpressionEvaluator.scala
- src/main/scala/firrtl_interpreter/real/DspRealBlackBox.scala
- src/test/scala/firrtl_interpreter/BlackBoxOutputSpec.scala
THIS BREAKS EXISTING API.  EXECUTE CALL NOW REQUIRES OUTPUT NAME
- Add output name to execute method
- Better doc in black box implementation
- Added some more tests of black boxes with multiple outputs and internal state
- Fixed problem where black boxes with no input dependencies did not work
- Updated internal examples that used black boxes
> Fix BlackBox problem when box has multiple outputs Issue 84

- .gitignore
- src/main/scala/firrtl_interpreter/Driver.scala
- src/main/scala/firrtl_interpreter/FirrtlRepl.scala
- src/main/scala/firrtl_interpreter/FirrtlTerp.scala
- src/main/scala/firrtl_interpreter/InterpretiveTester.scala
- src/main/scala/firrtl_interpreter/ToLoFirrtl.scala
- src/main/scala/firrtl_interpreter/VcdReplayTester.scala
- src/test/scala/firrtl_interpreter/BlackBoxOutputSpec.scala
- src/test/scala/firrtl_interpreter/LifeCellSpec.scala
- src/test/scala/firrtl_interpreter/RegisterSpec.scala
- src/test/scala/firrtl_interpreter/real/BlackBoxRealSpec.scala
The interpreter was not picking up the disable combinational loop detection command line flag.
The default initial lowering pass now picks up this flag.
This required a lot of manipulation of the optionsManager traits
Which affected many files in main and test.
Affected many imports as well.
Fixed flag which disabled default initial lowering pass
> This breaks API for chisel testers.  A matched PR from there must be done when this is done
> Problem disabling Combinational Loop Detection

- build.sbt
- project/build.properties
To clean, test, and build Scala 2.11 and Scala 2.12 versions:
% sbt +clean +test +publishLocal
NOTE: You need to be running Java 8 to build the 2.12 version.
> Update sbt to 0.13.16; add Scala 2.12 support.

- src/main/scala/firrtl_interpreter/InterpretiveTester.scala
- src/main/scala/firrtl_interpreter/Memory.scala
- src/test/scala/firrtl_interpreter/MemoryUsageSpec.scala
Added pokeMemory and peekMemory to InterpretiveTester
Added Memory#forceWrite to make this easier to do.
Added tests to show poking and peeking
This is an interpreter only fix for [/chisel-testers/issues/166](https://github.com/freechipsproject/chisel-testers/issues/166)
> pokeMemory and peekMemory allow testers to directly set values in memories

- src/main/scala/firrtl_interpreter/DependencyGraph.scala
- src/main/scala/firrtl_interpreter/ExternalModule.scala
- src/main/scala/firrtl_interpreter/real/DspRealBlackBox.scala
- src/test/scala/firrtl_interpreter/BlackBoxOutputSpec.scala
This fix
- More generally adds instance name as prefix to BB inputs
- Allows each black box to be a single instance.
- Deprecates the fullName function in BlackBoxImplementation
> BlackBoxImplentation instances must be distinct due to internal state

- src/main/scala/firrtl_interpreter/FirrtlTerp.scala
- src/main/scala/firrtl_interpreter/InterpretiveTester.scala
- src/test/scala/firrtl_interpreter/vcd/VCDSpec.scala
If write VCD is enabled and interpreter gets and exception
or a stop occurs in the circuit. Write out the VCD file if at all
possible.
> Will now write VCD log file even if errors or exceptions occur

- src/main/scala/firrtl_interpreter/FirrtlRepl.scala
Driver.executeFirrtlRepl(...) do not run on windows and report error:
-creating .firrtl_repl_history...
-java.io.IOException: The system cannot find the path specified
because interpreter code internal use System.getProperty("user.home") to get the user's home path as replacement string, but returned path include '\' unquoted. which lead to create file failed. with this fix, interactive interpreter run good on windows.
> Interactive FirrtlRepl do not run on windows.

- src/test/resources/VcdAdder.fir
- src/test/resources/three_deep.fir
Reset and Clock not being wired up caused initialization checks
connect clock and resets in three_deep.fir
connect clock in VcdAdder.fir
Could not produce error in Issue #106 but I am pretty sure this is the cause
> Fix CheckInitialization errors on clock and reset in tests

- src/test/scala/firrtl_interpreter/PoisonSpec.scala
Since firrtl now complains (freechipsproject/firrtl#587) about mixed-mode operations and assignments,
use the same type for Poison inputs and outputs.
> Use same type for PoisonSpec inputs

- src/main/scala/firrtl_interpreter/CircuitState.scala
- src/main/scala/firrtl_interpreter/vcd/VCD.scala
- src/test/scala/firrtl_interpreter/vcd/VCDSpec.scala
Now shows them in binary with MSB set
Fixes part of interpreter issue #109
> negative sints were not being recorded properly

- src/test/scala/firrtl_interpreter/PoisonSpec.scala
When firrtl was changed to disallow cross type primops
PoisonSpec was changed but not enough to avoid
some case where too big of numbers were passed into circuit.
Also changed test to use contains instead of printf to confirm
poison is displayed correctly
> Fix problem discovered by @ucbjrl in PoisonSpec

- src/main/scala/firrtl_interpreter/DependencyGraph.scala
- src/test/scala/firrtl_interpreter/BlackBoxOutputSpec.scala
When instance was more than one deep could have problems
could arise with with io naming.
This fixes that problem by using the proper name prefix.
Fixes a nearby code warning, that makes this file now clean.
Adds a test case that shows the bug is fixed.
> Fixed Black box implementation bug

- frepl.sh
- src/main/scala/firrtl_interpreter/Concrete.scala
- src/test/scala/firrtl_interpreter/ConcreteSpec.scala
Should fix Issue #122 
Added tests
- for not
- for toBinaryString and toHexString
Deprecated asBinaryString, in favor of new toBinaryString.
Also added toHexString.
> Fix Concrete#not method, described in Issue #122

- src/main/scala/firrtl_interpreter/vcd/VCD.scala
Width one 'x' wires must be written in
x{id}
format instead of
bx {id}
This causes GTKwave to fail parsing.
> Special case that must have accidentally been correct before.

- src/main/resources/META-INF/services/firrtl.options.RegisteredLibrary
- src/main/scala/firrtl_interpreter/VcdReplayOptions.scala
- src/main/scala/firrtl_interpreter/repl/ReplConfig.scala
- src/main/scala/firrtl_interpreter/vcd/VCDConfig.scala
Without this, the children of `RegisteredLibrary` aren't registered... The error is super annoying as there's no good way to know if the user added a bogus option or if they wrote a library and forgot to include a `src/main/resources/META-INF/services` entry. (With high probability it's the former due to the prior on the number of library writers.)
Note: this is only as an example of what is missing. I'm not entirely sure that all of these should be registered. They have long options that are duplicates. FIRRTL erroneously prints the error with their short duplicates. Fixing the FIRRTL PR now.
> ServiceLoader META-INF Interpreter, VcdReplay

- src/main/scala/firrtl_interpreter/Memory.scala
Error thrown if depth is bigger than an Int can be.
> Fixes Memory parsing error due to Firrtl Memory depth is now BigInt

- src/test/scala/firrtl_interpreter/fixedpoint/FixedPointSpec.scala
Problem is that treadle keeps raw firrtl around to run tests on.
- The internal api for set precision is now `setp` for both fixed point an interval
- `bpset` is now `setp`
> PrimOp changed in Intervals upstreaming

- src/test/scala/firrtl_interpreter/vcd/VCDSpec.scala
freechipsproject/firrtl@3c8e22dc9e4f033be167aa721e6d8ad54330ca3c extended BackendCompilationUtilities with LazyLogging which effectively undoes the effect of the `protected` in:
```scala
trait LazyLogging {
protected val logger = new Logger(this.getClass.getName)
}
```
which in turn causes compilation failures for code that expects `logger` to refer to the package, and not some local field.
> Deal with redefinition of logger due to BackendCompilationUtilities update

- .github/scripts/ExtractBuildDependenciesFromPullRequest.gawk
- .github/scripts/generateGitClones.gawk
- .github/scripts/generateVersionOverrides.gawk
- .github/workflows/test.yml
Add gawk scripts to parse conditional build dependencies specified in Pull Request bodies in the form of:
```
Build with: git-clone chisel3 https://github.com/freechipsproject/chisel3.git master
Build with: maven-version firrtl 1.3-SNAPSHOT
```
where:
- `git-clone` specifies a GitHub repository to `git clone` and `publishLocal` prior to building the proposed pull request,
- `maven-version` specifies a version override which will add be added to the `sbt` command line as follows:
```
sbt -DfirrtlVersion=1.3-SNAPSHOT
```
under the assumption that the `build.sbt` supports such an override.
**NOTE**: the comments in the body of this PR should trigger both build dependency styles.
> Add support for GitHub Workflows.

- build.sbt
Since the .scala-steward.conf file doesn't appear to be working (as far as ignoring Berkeley artifacts goes), try the technique mentioned in https://github.com/fthomas/scala-steward/blob/d8e1fd39007fefdb251ec0f07887964cd75a0962/docs/repo-specific-configuration.md
> Another attempt to have ScalaSteward ignore chisel dependencies.

- src/main/scala/firrtl/Driver.scala
- src/main/scala/firrtl/ExecutionOptionsManager.scala
- src/main/scala/firrtl/stage/package.scala
- src/main/scala/firrtl/stage/phases/DriverCompatibility.scala
- src/main/scala/firrtl_interpreter/Driver.scala
- src/main/scala/firrtl_interpreter/FirrtlRepl.scala
- src/main/scala/firrtl_interpreter/FirrtlTerp.scala
- src/main/scala/firrtl_interpreter/InterpretiveTester.scala
- src/main/scala/firrtl_interpreter/ReplConfig.scala
- src/test/scala/firrtl_interpreter/vcd/VCDSpec.scala
Same idea as https://github.com/freechipsproject/chisel-testers/pull/322. I actually just copied the files from chisel-testers in `src/main/scala/firrtl` which means I will need to delete them from chisel-testers to avoid classpath conflicts.
This enables firrtl-interpreter to "work" (as far as it still actually works) for the 3.5.0 release cycle.
> Polyfill removed APIs and deprecate APIs, this project is end-of-life.
